# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'LavaSDK' do

pod 'XMPPFramework'
pod 'Alamofire' 
pod 'AlamofireObjectMapper'
pod 'ObjectMapper'
pod 'XCGLogger'
pod 'ReachabilitySwift'
pod 'AlamofireImage'

end

target 'LavaSDKTests' do

end

post_install do |installer_representation|
    installer_representation.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
        end
    end
end